// js/ui.js

// --- Unified Page Templates ---
export const perencanaanMenuTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="border-b border-gray-200"><nav class="-mb-px flex space-x-6" id="planning-tabs"><button data-tab="resep" class="tab-button tab-active whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm">Daftar Resep</button><button data-tab="siklus" class="tab-button whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300">Kalender Menu Bulanan</button></nav></div><div id="planning-content" class="mt-6"></div></div>`;
export const produksiStokTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="border-b border-gray-200"><nav class="-mb-px flex space-x-6" id="production-tabs"><button data-tab="stok" class="tab-button tab-active whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm">Stok Inventaris</button><button data-tab="produksi" class="tab-button whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300">Perintah Kerja (WO)</button><button data-tab="item" class="tab-button whitespace-nowrap py-3 px-1 border-b-2 font-medium text-sm border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300">Master Item</button></nav></div><div id="production-content" class="mt-6"></div></div>`;

// --- Tab Content ---
export const resepTabContent = `<div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Daftar Resep</h3><button onclick="openRecipeModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center"><svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>Tambah Resep</button></div><div id="recipeList" class="space-y-3"></div>`;
export const stokTabContent = `<div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Daftar Stok Inventaris</h3><input type="text" id="stockSearchInput" placeholder="Cari nama item..." class="w-full md:w-1/3 px-4 py-2 border rounded-lg"></div><div class="overflow-x-auto"><table class="w-full text-sm text-left"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">Nama Item</th><th class="px-6 py-3 text-center">Total Stok</th><th class="px-6 py-3">Kedaluwarsa Terdekat</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="stockTableBody"></tbody></table></div>`;
export const produksiTabContent = `<div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Perintah Kerja</h3><button onclick="openWorkOrderModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center"><svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>Buat WO</button></div><div id="workOrderList" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"></div>`;
export const masterItemTabContent = `<div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Master Data Item</h3><button onclick="openItemModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center"><svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>Tambah Item</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">ID</th><th class="px-6 py-3">Nama Item</th><th class="px-6 py-3">Unit</th><th class="px-6 py-3 text-right">Harga</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="master-items-table"></tbody></table></div>`;
export const siklusMenuTabContent = `
<div class="flex flex-col md:flex-row justify-between items-center mb-4">
    <div class="flex items-center gap-4">
        <button id="prevMonthBtn" class="p-2 rounded-full hover:bg-gray-200">
            <svg class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
            </svg>
        </button>
        <h3 class="text-xl font-semibold w-48 text-center" id="monthYearDisplay"></h3>
        <button id="nextMonthBtn" class="p-2 rounded-full hover:bg-gray-200">
            <svg class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
            </svg>
        </button>
    </div>
    <button id="saveSiklusButton" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm mt-4 md:mt-0">Simpan Jadwal</button>
</div>
<div class="grid grid-cols-7 gap-px mt-4 bg-gray-200 border border-gray-200 rounded-lg overflow-hidden">
    <div class="text-center font-semibold text-sm py-2 bg-gray-50 text-gray-600">Min</div>
    <div class="text-center font-semibold text-sm py-2 bg-gray-50 text-gray-600">Sen</div>
    <div class="text-center font-semibold text-sm py-2 bg-gray-50 text-gray-600">Sel</div>
    <div class="text-center font-semibold text-sm py-2 bg-gray-50 text-gray-600">Rab</div>
    <div class="text-center font-semibold text-sm py-2 bg-gray-50 text-gray-600">Kam</div>
    <div class="text-center font-semibold text-sm py-2 bg-gray-50 text-gray-600">Jum</div>
    <div class="text-center font-semibold text-sm py-2 bg-gray-50 text-gray-600">Sab</div>
</div>
<div id="siklusMenuGrid" class="grid grid-cols-7 gap-px bg-gray-200 border-l border-r border-b border-gray-200 rounded-b-lg">
</div>`;


// --- Standalone Page Templates ---
export const pengadaanPageTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex flex-col md:flex-row justify-between items-center mb-4 gap-4"><div class="w-full md:w-1/3"><input type="text" id="searchInputPO" placeholder="Cari No. PO atau Supplier..." class="w-full px-4 py-2 border rounded-lg"></div><div class="flex items-center gap-2 w-full md:w-auto"><select id="statusFilterPO" class="px-4 py-2 border rounded-lg"><option value="all">Semua Status</option><option value="Draft">Draft</option><option value="Disetujui">Disetujui</option><option value="Diterima Sebagian">Diterima Sebagian</option><option value="Diterima Penuh">Diterima Penuh</option></select><button id="createPOButton" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold flex items-center whitespace-nowrap"><svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>Buat PO</button></div></div><div class="overflow-x-auto"><table class="w-full text-sm text-left"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">No. PO</th><th class="px-6 py-3">Supplier</th><th class="px-6 py-3">Tgl Pesan</th><th class="px-6 py-3 text-right">Total</th><th class="px-6 py-3 text-center">Status</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="poTableBody"></tbody></table></div></div>`;
export const keuanganPageTemplate = `<div class="grid grid-cols-1 lg:grid-cols-3 gap-6"><div class="lg:col-span-2 bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Riwayat Transaksi</h3><button onclick="openKeuanganModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm">Tambah Transaksi</button></div><div class="overflow-y-auto max-h-96"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100 sticky top-0"><tr><th class="px-6 py-3">Tanggal</th><th class="px-6 py-3">Deskripsi</th><th class="px-6 py-3 text-right">Pemasukan</th><th class="px-6 py-3 text-right">Pengeluaran</th></tr></thead><tbody id="finance-transactions-table"></tbody></table></div></div><div class="bg-white p-6 rounded-lg shadow-md self-start"><h3 class="text-lg font-semibold mb-4">Ringkasan Keuangan</h3><div class="space-y-4"><div class="flex justify-between"><span class="text-gray-600">Total Pemasukan:</span><span id="total-pemasukan" class="font-semibold text-green-600"></span></div><div class="flex justify-between"><span class="text-gray-600">Total Pengeluaran:</span><span id="total-pengeluaran" class="font-semibold text-red-600"></span></div><hr><div class="flex justify-between text-lg"><span class="font-bold">Saldo Akhir:</span><span id="saldo-akhir" class="font-bold"></span></div></div></div></div>`;
export const pelaporanPageTemplate = `<div><div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-6"><div class="bg-white p-5 rounded-lg shadow"><h4 class="text-sm font-medium text-gray-500">Porsi Terdistribusi</h4><p class="text-3xl font-bold mt-1" id="kpi-total-porsi">0</p><p class="text-xs text-gray-500 mt-1">hari ini</p></div><div class="bg-white p-5 rounded-lg shadow"><h4 class="text-sm font-medium text-gray-500">Kehadiran Karyawan</h4><p class="text-3xl font-bold mt-1" id="kpi-attendance-rate">0%</p><p class="text-xs text-gray-500 mt-1" id="kpi-attendance-detail">0 dari 0 karyawan</p></div><div class="bg-white p-5 rounded-lg shadow"><h4 class="text-sm font-medium text-gray-500">Total Pengadaan</h4><p class="text-3xl font-bold mt-1" id="kpi-total-procurement">Rp 0</p><p class="text-xs text-gray-500 mt-1">bulan ini</p></div><div class="bg-white p-5 rounded-lg shadow"><h4 class="text-sm font-medium text-gray-500">Total Pengeluaran</h4><p class="text-3xl font-bold mt-1" id="kpi-total-expense">Rp 0</p><p class="text-xs text-gray-500 mt-1">bulan ini</p></div></div></div>`;
export const laporanPengantaranTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4 no-print"><h3 class="text-lg font-semibold">Laporan Pengantaran</h3><div class="flex items-center gap-2"><label class="text-sm">Tanggal:</label><input type="date" id="laporan-tanggal" class="border rounded-lg p-2 text-sm"><button id="printLaporanBtn" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 text-sm">Cetak Laporan</button></div></div><div id="laporan-content" class="space-y-4"></div></div>`;
export const asetPageTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Manajemen Aset</h3><button onclick="openAsetModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center">Tambah Aset</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">Nama Aset</th><th class="px-6 py-3">Kategori</th><th class="px-6 py-3">Tgl Beli</th><th class="px-6 py-3 text-right">Nilai</th><th class="px-6 py-3 text-center">Status</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="aset-table-body"></tbody></table></div></div>`;
export const masterKaryawanTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Master Data Karyawan</h3><button onclick="openKaryawanModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center">Tambah Karyawan</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">Nama</th><th class="px-6 py-3">Posisi</th><th class="px-6 py-3">Tgl Bergabung</th><th class="px-6 py-3 text-center">Status</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="karyawanTableBody"></tbody></table></div></div>`;
export const gajiContentTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Manajemen Gaji Karyawan</h3><button onclick="openGajiModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center">Buat Gaji Baru</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">Nama Karyawan</th><th class="px-6 py-3">Periode</th><th class="px-6 py-3 text-right">Gaji Bersih</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="gajiTableBody"></tbody></table></div></div>`;
export const absensiContentTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Absensi Karyawan</h3><div class="flex items-center gap-2"><label class="text-sm">Tanggal:</label><input type="date" id="absensiDate" class="border rounded-lg p-2 text-sm"></div></div><div id="absensiList" class="divide-y border rounded-lg"></div><div class="mt-6 flex justify-end"><button id="saveAbsensiButton" class="bg-blue-600 text-white font-semibold py-2 px-6 rounded-lg hover:bg-blue-700">Simpan Absensi</button></div></div>`;
export const masterSuppliersTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Master Data Supplier</h3><button onclick="openSupplierModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center">Tambah Supplier</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">Nama Perusahaan</th><th class="px-6 py-3">Kontak Person</th><th class="px-6 py-3">Telepon</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="master-suppliers-table"></tbody></table></div></div>`;
export const masterSchoolsTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Master Data Sekolah</h3><button onclick="openSchoolModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center">Tambah Sekolah</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">Nama Sekolah</th><th class="px-6 py-3">Kepala Sekolah</th><th class="px-6 py-3">Telepon</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="master-schools-table"></tbody></table></div></div>`;
export const masterUsersTemplate = `<div class="bg-white p-6 rounded-lg shadow-md"><div class="flex justify-between items-center mb-4"><h3 class="text-lg font-semibold">Master Data Pengguna</h3><button onclick="openUserModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center">Tambah Pengguna</button></div><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-6 py-3">Nama</th><th class="px-6 py-3">Peran</th><th class="px-6 py-3 text-center">Aksi</th></tr></thead><tbody id="master-users-table"></tbody></table></div></div>`;
export const distribusiPageTemplate = `<div class="bg-white p-6 rounded-lg shadow-md">
    <div class="flex flex-col md:flex-row justify-between items-center mb-4 gap-4">
        <h3 class="text-lg font-semibold">Jadwal Pengiriman</h3>
        <div class="flex items-center gap-2">
            <label class="text-sm">Dari:</label>
            <input type="date" id="distribusiStartDate" class="border rounded-lg p-2 text-sm">
            <label class="text-sm">Sampai:</label>
            <input type="date" id="distribusiEndDate" class="border rounded-lg p-2 text-sm">
            <button onclick="openShipmentModal()" class="bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 font-semibold text-sm flex items-center">
                <svg class="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/></svg>
                Buat
            </button>
        </div>
    </div>
    <div id="shipmentList" class="space-y-4"></div>
</div>`;
export const masterContentTemplate = `<div id="master-content" class="p-4 md:p-6"></div>`;
export const kalenderPageTemplate = `
<div class="bg-white p-6 rounded-lg shadow-md">
  <div class="flex flex-col md:flex-row justify-between items-center mb-6 gap-4">
    <h3 class="text-xl font-semibold">Kalender Menu</h3>
    <div class="flex items-center gap-4">
      <button id="prevMonth" class="p-2 rounded-full hover:bg-gray-100">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7"></path>
        </svg>
      </button>
      <h4 id="currentMonth" class="text-lg font-medium"></h4>
      <button id="nextMonth" class="p-2 rounded-full hover:bg-gray-100">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"></path>
        </svg>
      </button>
      <button id="saveMenuCalendar" class="bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 font-semibold text-sm">
        Simpan
      </button>
    </div>
  </div>
  
  <div class="grid grid-cols-7 gap-0 border border-gray-200 rounded-lg overflow-hidden">
    <div class="bg-gray-100 p-2 text-center font-semibold">Min</div>
    <div class="bg-gray-100 p-2 text-center font-semibold">Sen</div>
    <div class="bg-gray-100 p-2 text-center font-semibold">Sel</div>
    <div class="bg-gray-100 p-2 text-center font-semibold">Rab</div>
    <div class="bg-gray-100 p-2 text-center font-semibold">Kam</div>
    <div class="bg-gray-100 p-2 text-center font-semibold">Jum</div>
    <div class="bg-gray-100 p-2 text-center font-semibold">Sab</div>
    <div id="calendarBody" class="col-span-7 grid grid-cols-7"></div>
  </div>
</div>
`;
export const modalsTemplate = `
    <div x-show="$store.modals.po" @keydown.escape.window="$store.modals.po = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.po = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-4xl max-h-full overflow-y-auto transform"><form id="poForm"><input type="hidden" id="poId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitlePO"></h3></div><div class="p-6 space-y-6"><div class="grid grid-cols-1 md:grid-cols-2 gap-6"><div><label for="supplier" class="block mb-2 text-sm font-medium">Supplier</label><select id="supplier" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></select></div><div><label for="orderDate" class="block mb-2 text-sm font-medium">Tanggal Pesan</label><input type="date" id="orderDate" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div></div><h4 class="text-lg font-semibold border-t pt-4">Item Pesanan</h4><div id="itemLines" class="space-y-4"></div><button type="button" id="addItemButton" class="text-blue-600 hover:text-blue-800 font-semibold text-sm flex items-center"><svg class="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>Tambah Item</button><div class="border-t pt-4 flex justify-end"><div class="text-right"><span class="text-sm text-gray-500">Total</span><p id="totalAmount" class="text-2xl font-bold">Rp 0</p></div></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.po = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.receipt" @keydown.escape.window="$store.modals.receipt = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.receipt = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-5xl max-h-full overflow-y-auto transform"><form id="receiptForm"><input type="hidden" id="receiptPoId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="receiptModalTitle"></h3></div><div class="p-6"><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-4 py-3">Item</th><th class="px-4 py-3 text-center">Dipesan</th><th class="px-4 py-3 text-center">Diterima Sblmnya</th><th class="px-4 py-3">Jml Diterima</th><th class="px-4 py-3">No. Lot</th><th class="px-4 py-3">Tgl. Kedaluwarsa</th></tr></thead><tbody id="receiptItemLines"></tbody></table></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.receipt = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan Penerimaan</button></div></form></div></div>
    <div x-show="$store.modals.lotDetail" @keydown.escape.window="$store.modals.lotDetail = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.lotDetail = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-full overflow-y-auto transform"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="lotModalTitle"></h3></div><div class="p-6"><div class="overflow-x-auto"><table class="w-full text-sm"><thead class="text-xs text-gray-700 uppercase bg-gray-100"><tr><th class="px-4 py-3">No. Lot</th><th class="px-4 py-3 text-center">Jumlah</th><th class="px-4 py-3">Tgl. Diterima</th><th class="px-4 py-3">Tgl. Kedaluwarsa</th></tr></thead><tbody id="lotDetailTableBody"></tbody></table></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.lotDetail = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5">Tutup</button></div></div></div>
    <div x-show="$store.modals.workOrder" @keydown.escape.window="$store.modals.workOrder = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.workOrder = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="workOrderForm"><input type="hidden" id="workOrderId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleWO"></h3></div><div class="p-6 space-y-4"><div><label for="woRecipeId" class="block mb-2 text-sm font-medium">Resep</label><select id="woRecipeId" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></select></div><div><label for="woTargetQuantity" class="block mb-2 text-sm font-medium">Target Kuantitas (Porsi)</label><input type="number" id="woTargetQuantity" min="1" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="woProductionDate" class="block mb-2 text-sm font-medium">Tanggal Produksi</label><input type="date" id="woProductionDate" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.workOrder = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.shipment" @keydown.escape.window="$store.modals.shipment = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.shipment = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-3xl max-h-full overflow-y-auto transform"><form id="shipmentForm"><input type="hidden" id="shipmentId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleShipment"></h3></div><div class="p-6 space-y-4"><div class="grid grid-cols-1 md:grid-cols-2 gap-4"><div><label for="shipmentDriverId" class="block mb-2 text-sm font-medium">Driver</label><select id="shipmentDriverId" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></select></div><div><label for="shipmentVehicleId" class="block mb-2 text-sm font-medium">Kendaraan</label><select id="shipmentVehicleId" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></select></div></div><div><label for="shipmentRecipeId" class="block mb-2 text-sm font-medium">Menu yang Dikirim</label><select id="shipmentRecipeId" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></select></div><h4 class="text-lg font-semibold border-t pt-4">Tujuan Pengiriman</h4><div id="deliveryLines" class="space-y-3"></div><button type="button" id="addDeliveryLineButton" class="text-blue-600 hover:text-blue-800 font-semibold text-sm flex items-center"><svg class="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>Tambah Tujuan</button></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.shipment = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan Pengiriman</button></div></form></div></div>
    <div x-show="$store.modals.recipeDetail" @keydown.escape.window="$store.modals.recipeDetail = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.recipeDetail = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg max-h-full overflow-y-auto transform"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="recipeDetailModalTitle"></h3></div><div class="p-6"><h4 class="font-semibold text-gray-700 mb-2">Bahan per Porsi</h4><ul id="recipeBomList" class="list-disc list-inside space-y-1 text-gray-600"></ul><h4 class="font-semibold text-gray-700 mt-4 mb-2">Informasi Gizi (per porsi)</h4><div id="recipeNutritionInfo" class="grid grid-cols-2 gap-2 text-sm"></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.recipeDetail = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5">Tutup</button></div></div></div>
    <div x-show="$store.modals.recipeForm" @keydown.escape.window="$store.modals.recipeForm = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.recipeForm = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-full overflow-y-auto transform"><form id="recipeForm"><input type="hidden" id="recipeId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleRecipe"></h3></div><div class="p-6 space-y-4"><div><label for="recipeName" class="block mb-2 text-sm font-medium">Nama Resep</label><input type="text" id="recipeName" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><h4 class="text-lg font-semibold border-t pt-4">Bahan-bahan (per porsi)</h4><div id="recipeIngredients" class="space-y-3"></div><button type="button" id="addIngredientButton" class="text-blue-600 hover:text-blue-800 font-semibold text-sm flex items-center"><svg class="h-5 w-5 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v3m0 0v3m0-3h3m-3 0H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>Tambah Bahan</button></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.recipeForm = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan Resep</button></div></form></div></div>
    <div x-show="$store.modals.siklusMenu" @keydown.escape.window="$store.modals.siklusMenu = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.siklusMenu = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-md transform"><form id="siklusMenuForm"><input type="hidden" id="siklusDate"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleSiklus"></h3></div><div class="p-6"><label for="siklusRecipeId" class="block mb-2 text-sm font-medium">Pilih Resep</label><select id="siklusRecipeId" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"></select></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.siklusMenu = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Pilih</button></div></form></div></div>
    <div x-show="$store.modals.karyawan" @keydown.escape.window="$store.modals.karyawan = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.karyawan = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="karyawanForm"><input type="hidden" id="karyawanId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleKaryawan"></h3></div><div class="p-6 space-y-4"><div><label for="karyawanNama" class="block mb-2 text-sm font-medium">Nama Lengkap</label><input type="text" id="karyawanNama" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="karyawanPosisi" class="block mb-2 text-sm font-medium">Posisi</label><input type="text" id="karyawanPosisi" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="karyawanTglBergabung" class="block mb-2 text-sm font-medium">Tanggal Bergabung</label><input type="date" id="karyawanTglBergabung" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="karyawanStatus" class="block mb-2 text-sm font-medium">Status</label><select id="karyawanStatus" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"><option value="Aktif">Aktif</option><option value="Tidak Aktif">Tidak Aktif</option></select></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.karyawan = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.gaji" @keydown.escape.window="$store.modals.gaji = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.gaji = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="gajiForm"><input type="hidden" id="gajiId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleGaji"></h3></div><div class="p-6 space-y-4"><div><label for="gajiKaryawanId" class="block mb-2 text-sm font-medium">Karyawan</label><select id="gajiKaryawanId" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></select></div><div><label for="gajiPeriode" class="block mb-2 text-sm font-medium">Periode</label><input type="month" id="gajiPeriode" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="gajiPokok" class="block mb-2 text-sm font-medium">Gaji Pokok</label><input type="number" id="gajiPokok" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="gajiTunjangan" class="block mb-2 text-sm font-medium">Tunjangan</label><input type="number" id="gajiTunjangan" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="gajiPotongan" class="block mb-2 text-sm font-medium">Potongan</label><input type="number" id="gajiPotongan" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.gaji = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    
    <div x-show="$store.modals.item" @keydown.escape.window="$store.modals.item = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.item = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="itemForm"><input type="hidden" id="itemId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleItem"></h3></div><div class="p-6 space-y-4"><div><label for="itemName" class="block mb-2 text-sm font-medium">Nama Item</label><input type="text" id="itemName" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div class="grid grid-cols-2 gap-4"><div><label for="itemUnit" class="block mb-2 text-sm font-medium">Unit (e.g., kg, liter)</label><input type="text" id="itemUnit" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="itemPrice" class="block mb-2 text-sm font-medium">Harga</label><input type="number" id="itemPrice" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.item = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.supplier" @keydown.escape.window="$store.modals.supplier = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.supplier = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="supplierForm"><input type="hidden" id="supplierId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleSupplier"></h3></div><div class="p-6 space-y-4"><div><label for="supplierName" class="block mb-2 text-sm font-medium">Nama Perusahaan</label><input type="text" id="supplierName" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="supplierContact" class="block mb-2 text-sm font-medium">Nama Kontak Person</label><input type="text" id="supplierContact" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"></div><div class="grid grid-cols-2 gap-4"><div><label for="supplierPhone" class="block mb-2 text-sm font-medium">Telepon</label><input type="tel" id="supplierPhone" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"></div><div><label for="supplierEmail" class="block mb-2 text-sm font-medium">Email</label><input type="email" id="supplierEmail" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"></div></div><div><label for="supplierAddress" class="block mb-2 text-sm font-medium">Alamat</label><input id="supplierAddress" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.supplier = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.school" @keydown.escape.window="$store.modals.school = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.school = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="schoolForm"><input type="hidden" id="schoolId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleSchool"></h3></div><div class="p-6 space-y-4"><div><label for="schoolName" class="block mb-2 text-sm font-medium">Nama Sekolah</label><input type="text" id="schoolName" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="schoolPrincipal" class="block mb-2 text-sm font-medium">Nama Kepala Sekolah</label><input type="text" id="schoolPrincipal" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"></div><div><label for="schoolPhone" class="block mb-2 text-sm font-medium">Telepon</label><input type="tel" id="schoolPhone" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5"></div><div><label for="schoolAddress" class="block mb-2 text-sm font-medium">Alamat</label><input id="schoolAddress" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.school = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.user" @keydown.escape.window="$store.modals.user = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.user = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="userForm"><input type="hidden" id="userId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleUser"></h3></div><div class="p-6 space-y-4"><div><label for="userName" class="block mb-2 text-sm font-medium">Nama Pengguna</label><input type="text" id="userName" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="userRole" class="block mb-2 text-sm font-medium">Peran</label><select id="userRole" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required><option value="Admin">Admin</option><option value="Manajer SPPG">Manajer SPPG</option><option value="Operator Sekolah">Operator Sekolah</option><option value="Driver">Driver</option><option value="Ahli Gizi">Ahli Gizi</option></select></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.user = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.aset" @keydown.escape.window="$store.modals.aset = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.aset = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="asetForm"><input type="hidden" id="asetId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleAset"></h3></div><div class="p-6 space-y-4"><div><label for="asetName" class="block mb-2 text-sm font-medium">Nama Aset</label><input type="text" id="asetName" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="asetCategory" class="block mb-2 text-sm font-medium">Kategori</label><input type="text" id="asetCategory" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div class="grid grid-cols-2 gap-4"><div><label for="asetPurchaseDate" class="block mb-2 text-sm font-medium">Tanggal Beli</label><input type="date" id="asetPurchaseDate" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="asetValue" class="block mb-2 text-sm font-medium">Nilai (Rp)</label><input type="number" id="asetValue" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div></div><div><label for="asetStatus" class="block mb-2 text-sm font-medium">Status</label><select id="asetStatus" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required><option value="Baik">Baik</option><option value="Perlu Perbaikan">Perlu Perbaikan</option><option value="Rusak">Rusak</option></select></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.aset = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>
    <div x-show="$store.modals.keuangan" @keydown.escape.window="$store.modals.keuangan = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50" style="display: none;" x-transition><div @click.outside="$store.modals.keuangan = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-lg transform"><form id="keuanganForm"><input type="hidden" id="keuanganId"><div class="p-6 border-b"><h3 class="text-xl font-semibold" id="modalTitleKeuangan"></h3></div><div class="p-6 space-y-4"><div><label for="keuanganDate" class="block mb-2 text-sm font-medium">Tanggal</label><input type="date" id="keuanganDate" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div><label for="keuanganDescription" class="block mb-2 text-sm font-medium">Deskripsi</label><input type="text" id="keuanganDescription" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div><div class="grid grid-cols-2 gap-4"><div><label for="keuanganType" class="block mb-2 text-sm font-medium">Tipe</label><select id="keuanganType" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required><option value="Pemasukan">Pemasukan</option><option value="Pengeluaran">Pengeluaran</option></select></div><div><label for="keuanganAmount" class="block mb-2 text-sm font-medium">Jumlah (Rp)</label><input type="number" id="keuanganAmount" class="bg-gray-50 border border-gray-300 text-sm rounded-lg block w-full p-2.5" required></div></div></div><div class="flex items-center justify-end p-6 bg-gray-50 rounded-b-lg"><button type="button" @click="$store.modals.keuangan = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5 mr-3">Batal</button><button type="submit" class="text-white bg-blue-600 hover:bg-blue-700 font-medium rounded-lg text-sm px-5 py-2.5">Simpan</button></div></form></div></div>

    <div x-show="$store.modals.deleteConfirm" @keydown.escape.window="$store.modals.deleteConfirm = false" class="modal-backdrop fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-[60]" style="display: none;" x-transition><div @click.outside="$store.modals.deleteConfirm = false" class="modal-content bg-white rounded-lg shadow-xl w-full max-w-md transform"><div class="p-6 text-center"><svg class="mx-auto mb-4 text-gray-400 w-12 h-12" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" /></svg><h3 class="mb-5 text-lg font-normal text-gray-500" id="deleteConfirmMessage"></h3><button id="confirmDeleteButton" class="text-white bg-red-600 hover:bg-red-800 font-medium rounded-lg text-sm inline-flex items-center px-5 py-2.5 text-center mr-2">Ya, Hapus</button><button type="button" @click="$store.modals.deleteConfirm = false" class="text-gray-500 bg-white hover:bg-gray-100 rounded-lg border border-gray-200 text-sm font-medium px-5 py-2.5">Batal</button></div></div></div>
`;
